#!/bin/bash
dir=$(command ls -l $(dirname $0)/${0##*/} | cut -d">" -f2 | tr -d ' ')

cd $(dirname $0)
cd "${dir%/*}/../libexec"

if [ -z "$1" ]
then
	echo "$0 'server'"
	exit 1
fi

server=$1

echo "[start] clipboard share localhost<-> $server"
./clip-share_c2s.sh "$server" | ./clip-share_s2c.sh "$server"
echo "[end] clipboard share localhost<-> $server"
